### ISSUE TITLE
ModuleNotFoundError: No module named 'limit_aiogram'

### ISSUE THREAD

**Issue by MarsMinerstone** [chazovtema/limited_aiogram#1]
You should change README file.

There is import error

**Comment by chazovtema** [comment]
Fixed in https://github.com/chazovtema/limited_aiogram/commit/5a6ca0f868556c7df97bc1c6aaa6592e64c28614

**Comment by chazovtema** [comment]
Fixed in https://github.com/chazovtema/limited_aiogram/commit/5a6ca0f868556c7df97bc1c6aaa6592e64c28614
